### ISSUE TITLE
Basic MedMentions example does not work with latest medcat

### ISSUE THREAD

**Issue by ianroberts** [CogStack/MedCATtrainer#1]
When I follow the `docker-compose` instructions the API returns an error of `'CDB' object has no attribute 'cui_disamb_always'` - as far as I can tell from tracking through the code this is what will happen when you try and load a CDB file created by an older version of medcat into a system running a newer version of the module.

The webapp `requirements.txt` does not specify a particular medcat module version, are you able to document the correct version of medcat that needs to be used for the example to run out of the box?

**Comment by w-is-h** [comment]
Hi Ian, thank you for reporting this. We are reorganizing the repository slightly by the end of the week it should be usable again. Also, if you only want to enter some text and do annotations please use the MedCAT repository - there is also a demo available there.

**Comment by w-is-h** [comment]
This should be resolved with the latest version of the models.
