### ISSUE TITLE
Pressing enter/return in concept lookup for last span submits document

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#103]
When pressing enter/return when browsing the concept lookup dropdown, instead of confirming the highlighted concept (which we think is more intuitive), the document is submitted.

**Comment by tomolopolis** [comment]
hi @sandertan - which version of the Trainer are you running? 

If hit enter here having searched for 'heart' 
![Screenshot 2022-12-16 at 15 22 21](https://user-images.githubusercontent.com/6503604/208130645-dcef26fc-8206-4a9a-b4d0-7551d50d5db0.png)

It does select the concept. Granted it doesn't 'Add Term' when you select enter

**Comment by sandertan** [comment]
hi @tomolopolis , I just tried to reproduce this, and I think this is only an issue when all pre-annotated concepts in the document are annotated already, and the selected entity is either:
- the last pre-annotated entity and the user wants to select an alternative concept
- a new text span, and the user uses the "Add Term" functionality.

**Comment by tomolopolis** [comment]
thanks @sandertan - will check this out

**Comment by tomolopolis** [comment]
fixed in #126
