### ISSUE TITLE
Use MedCATTrainer as annotation tool (without pre-annotations)

### ISSUE THREAD

**Issue by gitrach** [CogStack/MedCATtrainer#108]
I would like to be able to use MedCATTrainer as an annotation tool to first create a gold-standard annotated dataset (with no pre-annotations), before then seeing how well MedCAT performs. Is it possible to give a dummy (blank) concept database to MedCAT, but still allow the solr instance to see the real concept database, so that the annotators can select concepts when adding annotations?

From my experiments it seems to be possible to give them both the same cdb, but not separate cdbs, but I'm open to any tips on how to achieve this in the current set up.

**Comment by tomolopolis** [comment]
hi @gitrach - you can do this right now. 

Upload the full model with concepts as listed here:  https://medcattrainer.readthedocs.io/en/latest/project_admin.html#concept-picker-cdb-concept-import

Create a new CDB with an empty source list here: https://github.com/CogStack/MedCAT/blob/master/medcat/cdb_maker.py
save the CDB to disk, and upload to Trainer, set this for your Project Annotate Entities CDB, and uncheck "Train Model on submit".

Details listed [here](https://medcattrainer.readthedocs.io/en/latest/project_admin.html#creating-an-annotation-project)

**Comment by gitrach** [comment]
@tomolopolis - my heartfelt thanks for this! I had tried different combinations of settings but had not found the correct placement of the dummy and real models.

**Comment by tomolopolis** [comment]
Do feel free to re-open this if you run into any issues - I'll make a note to improve the documentation, as that still needs some work for sure
