### ISSUE TITLE
403 Forbidden Issue while trying to download cdb

### ISSUE THREAD

**Issue by AnimeshRoy86** [CogStack/MedCATtrainer#12]
Medcattrainer is failing with 403 forbidden issue when I am trying to download trained CDB data.
http://localhost:8001/media/core_snomed_cdb_pjW1Zmf.dat

My installation is in windows 10 system. 

Downloading a newly uploaded cdb works but once it is trained it throws 403 Forbidden problem.

**Comment by tomolopolis** [comment]
Hi - thanks for raising, 
Looks like this is a bug. Not sure when this was introduced, but for the time being you can directly use the `docker cp` to move over the model to you native FS:
For example:
`docker cp <container_name>:<path to cdb> <dest path of copied file>`

to get the container name use `docker ps`. My running container name is medcattrainer_medcattrainer_1, so I just grabbed the default preloaded CDB with:

`docker cp medcattrainer_medcattrainer_1:/home/api/media/cdb-medmen.dat . `

I'll look into fixing the link soon on the admin panel.

**But** re-use of the models trained in the trainer might produce worse results than MedCAT models trained on the annotations collected via the trainer. The trainer uses a high learning rate so the active-learning kicks in fairly 'early' in the annotation process. This may cause it to make mistake / generalise worse than if you train outside of the trainer. To train an existing MedCAT model follow the tutorial provided in the MedCAT guides:

https://colab.research.google.com/drive/1zzV3XzFJ9ihhCJ680DaQV2QZ5XnHa06X#scrollTo=8v3KJC2k_ZS-

**Comment by AnimeshRoy86** [comment]
Thanks a lot for the quick response. Since, I am using demo local system as of now. So, I resolved the issue by changing file permission by chmod. 

I want to re-use the model after the correction has been made on the trainer webapp. I am definitely using snomed db to first annotate the documents via trainer. But invariably trainer picks up few wrong indications that has to be corrected. For, example Dr. which us a subscript for Dr is being picked up as Diabetic Ratinopathy. Do you think it will overfit in these scenarios also if I reuse post manual annotations correction?

Another part is that your documentation says the trainer does not save or train meta annotations? 
How do we handle meta annotations then? Any example or help will be greatly appreciated.

**Comment by tomolopolis** [comment]
No worries. 

You can use the model trained on the webapp, but you should be aware of potential issues due to the high learning rate used. The trainer is intended as an 'assisted annotator', where the ideal scenario is, there are 2 or 3 annotators on the 2 'cloned' projects (same project settings / dataset / model, but each annotator only sees there own annotations), once all documents have been annotated you calculate [IIA / Cohen's Kappa](https://github.com/CogStack/MedCATtrainer/blob/master/docs/Processing_Annotations.ipynb)

Then you download all annotations, (concept and meta annotations) and train / test a new MedCAT (concept recognition) and MetaCAT (meta annotation models). There you'll see test errors, possibly leading you to gather more annotations for certain concepts / instances of meta annotation. Examples of training both models are [here](https://colab.research.google.com/drive/1zzV3XzFJ9ihhCJ680DaQV2QZ5XnHa06X#scrollTo=duJXZbHsDqBP). Both MedCAT / MetaCAT training consume the downloaded JSON file provided by the trainer to train, so it should be relatively simple process.

**Comment by AnimeshRoy86** [comment]
Thanks for the link. It was exactly what I was looking for. Regarding the training, I am getting this error in multiple places at the time of training the cdb. Any idea or clue about the below error?
To handle this, I am using a try block for unsupervised training but it is reappearing again in  supervised training.


  File "<ipython-input-100-43e03964040e>", line 3, in <module>
    _ = cat(text)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\cat.py", line 92, in __call__
    return self.nlp(text)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\utils\spacy_pipe.py", line 53, in __call__
    return self.nlp(text)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 439, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\spacy_cat.py", line 433, in __call__
    self.cat_ann.add_ann(raw_name, tkns, doc, self.to_disamb, doc_words)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\basic_cat_ann.py", line 40, in add_ann
    self._cat._add_ann(cui, doc, tkns, acc=1, name=name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\spacy_cat.py", line 373, in _add_ann
    self._add_cntx_vec(cui, doc, tkns)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\spacy_cat.py", line 291, in _add_cntx_vec
    negs = self.vocab.get_negative_samples(n=self.CNTX_SPAN * 2)

  File "C:\ProgramData\Anaconda3\lib\site-packages\medcat\utils\vocab.py", line 99, in get_negative_samples
    inds = np.random.randint(0, len(self.unigram_table), n)

  File "mtrand.pyx", line 745, in numpy.random.mtrand.RandomState.randint

  File "_bounded_integers.pyx", line 1363, in numpy.random._bounded_integers._rand_int32

ValueError: low >= high

**Comment by AnimeshRoy86** [comment]
Any tutorial on how embeddings.npy,medmen-merges.txt,medmen-vocab.json were prepared?

**Comment by tomolopolis** [comment]
That looks like a numpy issue. What version of numpy are you using?

**Comment by AnimeshRoy86** [comment]
Yes. Most likely however the exact line is trying to generate a random numpy array where low number is 0 and high number is 0. I think the error may be occuring due to lack of negative samples. May be a bigger corpora will help. However, I am not an expert.

np.version.version
Out[74]: '1.18.1'

**Comment by w-is-h** [comment]
Answered here: https://github.com/CogStack/MedCAT/issues/3

Issue related to custom vocabularies in MedCAT.
