### ISSUE TITLE
Enable multiple users to work in the same instance of MedCATtrainer

### ISSUE THREAD

**Issue by gitrach** [CogStack/MedCATtrainer#124]
Currently in order for multiple users to log in to the same instance of MedCATtrainer, they need a single shared log-in to a PC, as the container cannot be shared by users. In a secure network (like in a university) users are not allowed to share accounts or passwords. This means that a full install is required for each user and the configuration must be carefully set up to ensure alignment. It would be nice if the MedCATtrainer container could be shared with other users.

**Comment by tomolopolis** [comment]
Hi Rachel,

Multiple user accounts with permissions to specific projects can already be
setup.

On the /admin screen selecting users, and add new allows for account
creation.

When creating projects, you can use shift + mouse click to select those
users that should have permission to view a given project.

To have the 'same' project for multiple users. First create project, then
clone it, and add the new user(s) to their own respective project.

I hope that answers your question.

Thanks,

**Comment by gitrach** [comment]
Hi Tom, 

Thanks for your response.

That is not quite what I am getting at.

Although multiple users can be set up in MedCATtrainer, in order for them to use that single instance, they must have a single log on for that PC, because if another user logs into that PC, they cannot access the MedCATtrainer container. Password sharing is not allowed, so MedCATtrainer then needs to be installed by each user, and it is a separate instance. 

Perhaps this is more an issue with docker containers than specifically MedCATtrainer, but it might be worth noting depending on how far you will take this.

All the best,

Rachel
