### ISSUE TITLE
Profile containers, is 8Gb of memory adequate (it should be!)

### ISSUE THREAD

**Issue by tomolopolis** [CogStack/MedCATtrainer#17]
Users have 8GB allocated for docker, but still experience significant load times when loading projects (i.e. MedCAT models), even for small models.

Profile to figure out where this is coming from

**Comment by sandertan** [comment]
Hi @tomolopolis I figured out what made the process slow for me (both 8GB and 16GB RAM in Docker): I uploaded a 15MB excel file as dataset (containing 100k lines) for one project. It caused the whole admin panel to slow down. Removing the dataset solved the issue.

So for my use case, it's not an issue anymore. A 100k dataset to annotate is not workable anyway :sweat_smile:.

**Comment by tomolopolis** [comment]
ah - ok good to know what the kind of limits are for annotating!
