### ISSUE TITLE
Save Button causes project to crash when opened up 

### ISSUE THREAD

**Issue by kawsarnoor** [CogStack/MedCATtrainer#22]
When the save button is pressed message appears saying 'failed to save model'. When the project opened up again it says there was an error loading the cdb.

**Comment by tomolopolis** [comment]
this is now fixed in v1 and saving of models is only available to admin / superuser folks (i.e. those with access to the admin screen)

**Comment by tomolopolis** [comment]
247d095476df03ef4b394d2e51d2f46fac29ac1f
