### ISSUE TITLE
Run the demo got internal error

### ISSUE THREAD

**Issue by penggaolai** [CogStack/MedCATtrainer#24]
I am trying to run the demo project on Mac. But I got the Internal Server Error. I see some error in the terminal:

nginx_1          | 2020/12/16 06:38:07 [error] 21#21: *4 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /api/prepare-documents/ HTTP/1.1", upstream: "http://172.18.0.2:8000/api/prepare-documents/", host: "localhost:8001", referrer: "http://localhost:8001/train-annotations/1/1"
medcattrainer    | DAMN ! worker 1 (pid: 37) died, killed by signal 9 :( trying respawn ...
medcattrainer    | Respawned uWSGI worker 1 (new pid: 38)

Any suggestions?

**Comment by tomolopolis** [comment]
Looks like it failed when processing the documents. /prepare_documents/ is the call made to run the configured MedCAT model on the projects set of documents.
To be clear - by Demo project you mean the example project that is pre-configured on initial build / run of the container?

**Comment by Siddhijain16** [comment]
Hi @tomolopolis ,
After installing medcat trainer, I was not able to find any demo project. I used instructions on the [GitHUB page ](https://github.com/CogStack/MedCATtrainer)
 
I am facing the following error:


At terminal (docker logs)
medcattrainer | Internal Server Error: /api/prepare-documents/
medcattrainer_nginx | 172.18.0.1 - - [20/May/2021:09:46:12 +0000] "POST /api/prepare-documents/ HTTP/1.1" 500 525 "http://localhost:8001/train-annotations/2/82" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36"
medcattrainer | [pid: 156|app: 0|req: 125/122] 172.18.0.3 () {60 vars in 1304 bytes} [Thu May 20 09:45:51 2021] POST /api/prepare-documents/ => generated 525 bytes in 20690 msecs (HTTP/1.0 500) 5 headers in 156 bytes (1 switches on core 0)

 

At MedCatTrainer UI

![image](https://user-images.githubusercontent.com/46879959/118958681-43897880-b97f-11eb-84aa-f42aa2361c01.png)

 

 

Internal Server Error

 

Full Error:

 

Traceback (most recent call last):
File "./api/views.py", line 284, in prepare_documents
CAT_MAP=CAT_MAP, project=project)
File "./api/utils.py", line 273, in get_medcat
cdb.config.parse_config_file(path=os.getenv("MEDCAT_CONFIG_FILE"))
File "/usr/local/lib/python3.7/site-packages/medcat/config.py", line 167, in parse_config_file
with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/configs/base.txt'

**Comment by tomolopolis** [comment]
hi - it looks like the config file for loading MedCAT is not on the container. 

Which docker-compose file did you use?

**Comment by Siddhijain16** [comment]
> hi - it looks like the config file for loading MedCAT is not on the container.
> 
> Which docker-compose file did you use?

https://cdn.githubraw.com/CogStack/MedCATtrainer/9fbd517e/docker-compose.yml

**Comment by tomolopolis** [comment]
did you use the install.sh or git clone &&  docker-compose up ?

I've just run the install script and it looks like there is an issue with it

**Comment by tomolopolis** [comment]
I'd recommend cloning the repo directly and using the compose file directly, that seems to be working my side

**Comment by Siddhijain16** [comment]
> did you use the install.sh or git clone && docker-compose up ?
> 
> I've just run the install script and it looks like there is an issue with it

I opened the install.sh script and copied it line by line , necessary stuff

**Comment by tomolopolis** [comment]
not sure what you mean. But the install script just downloads the docker-compose.yml and env files, dumps them to /tmp/mc_trainer then runs docker-compose up, there's a loop to check things are up etc, but that looks a little buggy,

When I get time I'll fix, but for the time being, if you clone the repo, then cd into the the dir and run, `docker-compose up` that will work.

**Comment by Siddhijain16** [comment]
Hi, @tomolopolis 
Thanks a lot, Your trick worked like a charm.Now, I have successfully got medcat trainer setup and working on my machine.
I wanted to create a model to detect use case oriented task like experiencer and negation .
It would be great, if you can guide me on this, or maybe share a quick idea .

Thanks in advance

**Comment by tomolopolis** [comment]
We have a series of walkthroughs in the tutorial section of the MedCAT repo:
https://github.com/CogStack/MedCAT/tree/master/tutorial

This includes using annotations collected from a trainer export to train MetAnnotation models.
