### ISSUE TITLE
need for serving from '/'

### ISSUE THREAD

**Issue by sandwitch** [CogStack/MedCATtrainer#25]
Hi,

I'm building a test environment for MedCattrainer on behalf of @sandertan from the dutch UMCU.
We would like to place all application ports behind a location based reverse-proxy , installed on the dockerhost. So the dockers only need to bind to 127.0.0.1 (localhost). Problem is that the translation from from '/' to '/location/ is not fluently. We can achieve this by using the sub_filter module from nginx and translate directories to the right location. However on '/' we get : `Invalid URL: /medcattrainer/, redirected to the MedCAT Home page`. My question is how bad is this for the application. Because in my opinion, everything is working correctly.

Love to here from you.

**Comment by tomolopolis** [comment]
Hi - by working correctly you mean you can open projects / submit documents etc?

This warning was included as users were having some confusion about where URLs that we were sending around to them, (often not including the trailing / and alike). But if your setup works then its no problem having that warning appear. Its purely driven by the frontend using the browser URL so if you're fronting with a reverse-proxy thats fine.

I'll see if I can make this warning configurable, as ideally this would be an env var that could be plumbed in I guess...

**Comment by tomolopolis** [comment]
#26

**Comment by tomolopolis** [comment]
I've fixed this in the latest release. Use a envrionment var BEHIND_RP=1, to signify the trainer is behind a reverse proxy and the warning will not be shown

**Comment by sandertan** [comment]
Thanks @tomolopolis !
