### ISSUE TITLE
Deleted files in admin panel are not deleted from disk

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#30]
Hi @tomolopolis I was running out of disk space where docker stores it volumes, so I moved all files in volumes `api-static`, `api-media` and `api-db` to a local disk that had plenty of space. I noticed that my `api-media` folder contained a lot CDB/Vocab and Data files that I thought I deleted. I tested it again, and it seems that although the admin panels says "Successfully deleted 2 vocabularys", the files are not removed from disk. Is this intended, a bug, or am I doing something wrong?

Kind regards,
Sander

**Comment by tomolopolis** [comment]
Hi @sandertan, thanks for reporting. I've got some time this week dedicated to a range of improvements to the trainer, so I'll fit this fix in.

Also an FYI - we're going with a new version of trainer based off of MedCATv1 soon. @w-is-h  may have mentioned it to you. Essentially, its a major revision (breaking change) to prior MedCAT, there will be a migration strategy for migrating from existing medcat / trainer installations

**Comment by sandertan** [comment]
Okay that's good to know about the next version of trainer. Looking forward to it!

**Comment by tomolopolis** [comment]
3f23ebfe125bbf8c9967fc8e706c11b86d493b2d

will be fixed in the next release

**Comment by tomolopolis** [comment]
latest release is out, and on DockerHub
