### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nay421** [CogStack/MedCATtrainer#39]
Hello,

I have followed the installation instruction, but when I tried to annotate the example dataset, I ran into the following error. 

Any advice would be highly appreciated!

Nay

Internal Server Error

Full Error:

Traceback (most recent call last):
  File "./api/views.py", line 284, in prepare_documents
    CAT_MAP=CAT_MAP, project=project)
  File "./api/utils.py", line 272, in get_medcat
    cdb = CDB.load(cdb_path)
  File "/usr/local/lib/python3.7/site-packages/medcat/cdb.py", line 377, in load
    config = Config.from_dict(data['config'])
KeyError: 'config'

**Comment by tomolopolis** [comment]
As discussed this was an issue around loading MedCAT v0.x models into the latest version of the trainer that is no longer compatible with MedCAT 0.x models. 

To use MedCAT v0.x models use the following docker-compose file:
`$ docker-compose -f docker-compose-mx0x.yml up`

This uses the latest built images with compatible versions / env vars for MedCAT v0.x
https://github.com/CogStack/MedCATtrainer/blob/master/docker-compose-mc0x.yml
