### ISSUE TITLE
docker-compose build produces an error

### ISSUE THREAD

**Issue by a2dsouza** [CogStack/MedCATtrainer#4]
After cloning the repo and running `docker-compose build', the process gets to step 9/11 before eventually producing this error:

ERROR: Service 'medcattrainer' failed to build: The command '/bin/sh -c pip install -r /home/requirements.txt' returned a non-zero code: 137

The complete output is attached. I'm running Mac OS Version 10.14.6.

[medcattrainer-docker-compose-log.txt](https://github.com/CogStack/MedCATtrainer/files/3791235/medcattrainer-docker-compose-log.txt)

**Comment by tomolopolis** [comment]
Hi - looks like your container VM is running out of memory when installing the python deps.
Try increasing the available memory to something like 8Gb. It only needs the extra memory during the build process. 

https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container

**Comment by a2dsouza** [comment]
Oh, perfect. Thank you... I resolved the problem by increasing the amount of memory under the Preferences menu of Docker Desktop.
