### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by mcubr1c** [CogStack/MedCATtrainer#43]
Hi, after installing the medcat trainer and following the instructions on the GitHUB page, I am facing the following error at the stage of annotation.

In terminal:
medcattrainer_nginx  | 172.18.0.1 - - [13/Jul/2021:16:24:52 +0000] "POST /api/prepare-documents/ HTTP/1.1" 502 552 "http://localhost:8001/train-annotations/3/1477" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
medcattrainer_nginx  | 2021/07/13 16:24:52 [error] 25#25: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /api/prepare-documents/ HTTP/1.1", upstream: "http://172.18.0.2:8000/api/prepare-documents/", host: "localhost:8001", referrer: "http://localhost:8001/train-annotations/3/1477"
medcattrainer        | DAMN ! worker 1 (pid: 90) died, killed by signal 9 :( trying respawn ...
medcattrainer        | Respawned uWSGI worker 1 (new pid: 91)

on the UI:
<img width="419" alt="Screenshot 2021-07-13 at 17 35 34" src="https://user-images.githubusercontent.com/80765073/125491259-ce81107b-9ae0-4f84-89ff-8f55aeda06c8.png">

I have seen a closed issue where it was suggested to clone the repo directly and use the compose file directly however this has not worked for me. 

Any ideas on how to resolve this? Thank you!

**Comment by tomolopolis** [comment]
Could you show the error from the app container? so run `docker logs ` and the container ID.
<pre>
$ docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                            NAMES
9ebf974b4529        cogstacksystems/medcat-trainer-nginx:latest   "/docker-entrypoint.…"   16 minutes ago      Up 16 minutes       80/tcp, 0.0.0.0:8001->8000/tcp   medcattrainer_nginx
04b06376a0b8        cogstacksystems/medcat-trainer:latest         "/home/run.sh"           16 minutes ago      Up 16 minutes       8000/tcp                         medcattrainer
$ docker logs 04b06376a0b8
</pre>

**Comment by mcubr1c** [comment]
I've just tried to re-run everything and I've now got a different error that's not letting me get to the stage of replicating my previous error! Not sure what's happened over night but now I'm seeing this when I run docker-compose up:

medcattrainer        | The above exception was the direct cause of the following exception:
medcattrainer        | 
medcattrainer        | Traceback (most recent call last):
medcattrainer        |   File "manage.py", line 21, in <module>
medcattrainer        |     main()
medcattrainer        |   File "manage.py", line 16, in main
medcattrainer        |     ) from exc
medcattrainer        | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
medcattrainer        | Traceback (most recent call last):
medcattrainer        |   File "/home/api/manage.py", line 10, in main
medcattrainer        |     from django.core.management import execute_from_command_line
medcattrainer        | ModuleNotFoundError: No module named 'django'
medcattrainer        | 
medcattrainer        | The above exception was the direct cause of the following exception:
medcattrainer        | 
medcattrainer        | Traceback (most recent call last):
medcattrainer        |   File "/home/api/manage.py", line 21, in <module>
medcattrainer        |     main()
medcattrainer        |   File "/home/api/manage.py", line 16, in main
medcattrainer        |     ) from exc
medcattrainer        | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
medcattrainer        | /home/run.sh: 21: /home/run.sh: uwsgi: not found
medcattrainer exited with code 127

I wasn't getting this yesterday which is strange...

**Comment by tomolopolis** [comment]
Hi - so looks like our DockerHub Autobuild is caching a dodgy build, so
although the build isn't failing, it's not actually installing any
dependencies hence the error.

I'm building a fresh image now and will tag with the latest build. Hold
tight and I'll get back to you when it's working again

**Comment by mcubr1c** [comment]
Ok no problem - thanks for the speedy response!

**Comment by tomolopolis** [comment]
Okay I've updated the v2.1.1 release tag with the :latest tag, which as of
my testing worked. Please try and re-pull the image, (i.e. docker rmi the
exisiting images and and try a docker-compose up again)

**Comment by mcubr1c** [comment]
Great. It works as normal now. Thanks a lot.

I've done the steps you mentioned for my initial error and these are the logs that I get from the moment I refresh:

[pid: 99|app: 0|req: 45/42] 172.18.0.3 () {56 vars in 1697 bytes} [Wed Jul 14 14:19:43 2021] GET /train-annotations/3/1477 => generated 962 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.ProjectAnnotateEntities'> PolymorphicQuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 99|app: 0|req: 46/43] 172.18.0.3 () {54 vars in 1648 bytes} [Wed Jul 14 14:19:44 2021] GET /api/project-annotate-entities/?id=3 => generated 483 bytes in 80 msecs (HTTP/1.0 200) 5 headers in 148 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 47/44] 172.18.0.3 () {56 vars in 1620 bytes} [Wed Jul 14 14:19:44 2021] GET /favicon.ico => generated 962 bytes in 2 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 99|app: 0|req: 48/45] 172.18.0.3 () {54 vars in 1626 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5 => generated 69451 bytes in 20 msecs (HTTP/1.0 200) 5 headers in 150 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 49/46] 172.18.0.3 () {54 vars in 1640 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=2 => generated 115832 bytes in 13 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 50/47] 172.18.0.3 () {54 vars in 1638 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=3 => generated 125283 bytes in 16 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 51/48] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=4 => generated 92517 bytes in 13 msecs (HTTP/1.0 200) 5 headers in 150 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 52/49] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=5 => generated 112232 bytes in 13 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 53/50] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=6 => generated 112189 bytes in 20 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 54/51] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=7 => generated 88852 bytes in 11 msecs (HTTP/1.0 200) 5 headers in 150 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 55/52] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:44 2021] GET /api/documents/?dataset=5&page=8 => generated 98272 bytes in 17 msecs (HTTP/1.0 200) 5 headers in 150 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 56/53] 172.18.0.3 () {54 vars in 1639 bytes} [Wed Jul 14 14:19:45 2021] GET /api/documents/?dataset=5&page=9 => generated 127373 bytes in 18 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 57/54] 172.18.0.3 () {54 vars in 1641 bytes} [Wed Jul 14 14:19:45 2021] GET /api/documents/?dataset=5&page=10 => generated 129000 bytes in 26 msecs (HTTP/1.0 200) 5 headers in 151 bytes (1 switches on core 0)
[pid: 99|app: 0|req: 58/55] 172.18.0.3 () {54 vars in 1641 bytes} [Wed Jul 14 14:19:45 2021] GET /api/documents/?dataset=5&page=11 => generated 66688 bytes in 23 msecs (HTTP/1.0 200) 5 headers in 150 bytes (1 switches on core 0)
DAMN ! worker 1 (pid: 99) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 100)

**Comment by tomolopolis** [comment]
doesn't look like there's any issues via that log, apart from it failing after loading 11 pages of dataset with id:5. You're still seeing the same error as originally posted? 

Is this trying to load one of the sample datasets or some other dataset you've uploaded yourself? If its one your own, how big is the dataset, i.e. how many documents? Also are you running the container on windows or a *nix system?

**Comment by mcubr1c** [comment]
Yes still seeing the same error - I was using my own dataset however it may have been too large. I just tried re-uploading a smaller dataset containing 10 documents however I still get the same error. I also just tried using the psych.csv sample dataset in a separate project but I still get the internal server error strangely

I'm running the container on macOS

**Comment by hhuang-syapse** [comment]
I'm having the same Internal Server Error. Any fix? 
Is there a way to make it multiprocess/threads? Thanks.

`CONTAINER ID   IMAGE                                         COMMAND                  CREATED         STATUS         PORTS                                               NAMES
3069ad9469dc   cogstacksystems/medcat-trainer-nginx:v2.1.1   "/docker-entrypoint.…"   4 minutes ago   Up 3 minutes   80/tcp, 0.0.0.0:8001->8000/tcp, :::8001->8000/tcp   medcattrainer_nginx
5df95785b794   cogstacksystems/medcat-trainer:v2.1.1         "/home/run.sh"           4 minutes ago   Up 3 minutes                                                       medcattrainer
`

The error log: 
`0 static files copied to '/home/api/static', 159 unmodified.
No changes detected
No changes detected in app 'api'
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, background_task, contenttypes, sessions
Running migrations:
  No migrations to apply.
Operations to perform:
  Apply all migrations: api
Running migrations:
  No migrations to apply.
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jul 16 21:42:39 2021] ***
compiled with version: 8.3.0 on 14 July 2021 10:00:50
os: Linux-5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021
nodename: medcat
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/api
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/api/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:40975 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.11 (default, Jun 29 2021, 20:31:06)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559dbb3e33a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x559dbb3e33a0 pid: 79 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 79)
spawned uWSGI worker 1 (pid: 95, cores: 1)
spawned uWSGI http 1 (pid: 96)
[pid: 95|app: 0|req: 1/1] 127.0.0.1 () {32 vars in 373 bytes} [Fri Jul 16 21:42:54 2021] GET /api/ => generated 964 bytes in 293 msecs (HTTP/1.1 200) 5 headers in 142 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 2/2] 127.0.0.1 () {36 vars in 456 bytes} [Fri Jul 16 21:42:55 2021] POST /api/api-token-auth/ => generated 52 bytes in 99 msecs (HTTP/1.1 200) 4 headers in 122 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.ConceptDB'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 95|app: 0|req: 3/3] 127.0.0.1 () {34 vars in 465 bytes} [Fri Jul 16 21:42:55 2021] GET /api/concept-dbs/ => generated 153 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 139 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Vocabulary'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 95|app: 0|req: 4/4] 127.0.0.1 () {34 vars in 455 bytes} [Fri Jul 16 21:42:55 2021] GET /api/vocabs/ => generated 113 bytes in 6 msecs (HTTP/1.1 200) 5 headers in 139 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Dataset'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 95|app: 0|req: 5/5] 127.0.0.1 () {34 vars in 459 bytes} [Fri Jul 16 21:42:55 2021] GET /api/datasets/ => generated 371 bytes in 6 msecs (HTTP/1.1 200) 5 headers in 127 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.ProjectAnnotateEntities'> PolymorphicQuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 95|app: 0|req: 6/6] 127.0.0.1 () {34 vars in 493 bytes} [Fri Jul 16 21:42:55 2021] GET /api/project-annotate-entities/ => generated 488 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 148 bytes (1 switches on core 0)
Checking for default projects / datasets / CDBs / Vocabs
Found at least one object amongst cdbs, vocabs, datasets & projects. Skipping example creation
[pid: 95|app: 0|req: 7/7] 172.18.0.3 () {56 vars in 1675 bytes} [Fri Jul 16 21:42:59 2021] GET / => generated 962 bytes in 12 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 8/8] 172.18.0.3 () {54 vars in 1581 bytes} [Fri Jul 16 21:42:59 2021] GET /api/behind-rp/ => generated 4 bytes in 7 msecs (HTTP/1.0 200) 5 headers in 134 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 9/9] 172.18.0.3 () {54 vars in 1613 bytes} [Fri Jul 16 21:42:59 2021] GET /api/project-annotate-entities/ => generated 488 bytes in 16 msecs (HTTP/1.0 200) 5 headers in 148 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 10/10] 172.18.0.3 () {54 vars in 1618 bytes} [Fri Jul 16 21:42:59 2021] GET /api/complete-projects/?projects=1 => generated 34 bytes in 14 msecs (HTTP/1.0 200) 5 headers in 135 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 11/11] 172.18.0.3 () {52 vars in 1541 bytes} [Fri Jul 16 21:42:59 2021] GET /favicon.ico => generated 962 bytes in 3 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 12/12] 172.18.0.3 () {54 vars in 1641 bytes} [Fri Jul 16 21:43:01 2021] GET /api/project-annotate-entities/?id=1 => generated 488 bytes in 28 msecs (HTTP/1.0 200) 5 headers in 148 bytes (1 switches on core 0)
[pid: 95|app: 0|req: 13/13] 172.18.0.3 () {52 vars in 1560 bytes} [Fri Jul 16 21:43:01 2021] GET /favicon.ico => generated 962 bytes in 2 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[pid: 95|app: 0|req: 14/14] 172.18.0.3 () {54 vars in 1619 bytes} [Fri Jul 16 21:43:01 2021] GET /api/documents/?dataset=2 => generated 4384 bytes in 15 msecs (HTTP/1.0 200) 5 headers in 149 bytes (1 switches on core 0)
DAMN ! worker 1 (pid: 95) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 97)
[pid: 97|app: 0|req: 16/15] 172.18.0.3 () {52 vars in 1563 bytes} [Fri Jul 16 21:43:13 2021] GET /favicon.ico => generated 962 bytes in 2579 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
`

**Comment by tomolopolis** [comment]
Hi sorry you're both seeing the same thing - not sure what you mean by multi-process / threads though and not sure that will help here.

how much memory have you allocated to docker? I'd recommend at least 8Gb. From the log the Django process looks like its being killed then restarted by uWSGI when loading documents.

**Comment by mcubr1c** [comment]
Unfortunately I still get the internal server error even after allocating 8Gb. Very strange! I'm not sure if this is related to my issue, but I built my own cdb following instructions in https://github.com/w-is-h/umls (after gaining access to the database from NLM) and it is able to annotate in python, although for some reason my model doesn't have any of the 'pretty names'. Would it be possible to gain access to your cdb.dat file incase there's something wrong with mine that might be causing this error?

**Comment by tomolopolis** [comment]
@mcubr1c  - is this still an issue?
