### ISSUE TITLE
Most fields in Concept Summary are n/a

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#48]
Hi @tomolopolis I stumbled upon another issue in current master: Most of the fields in the Concept Summary are n/a, while the API has retrieved data for it:

![image](https://user-images.githubusercontent.com/9624990/134910139-de4e782f-bdf7-4c79-9d37-e06319da74c9.png)

In the example it's also strange that pretty name contains the CUI. Is that because the CDB does not contain a `preferred_name` for that CUI?

**Comment by sandertan** [comment]
After setting the correct preferred name, most fields are still not used:

![image](https://user-images.githubusercontent.com/9624990/135830280-09b63ebe-4c5c-410e-a5db-33f9fac200db.png)

So if the pretty_name is absent (no `P` in name status column which fills the `preferred_name` field in CDB), the CUI is used as pretty name in the API (although not used in the front end). Perhaps it would be nice to show a random (the first) synonym in that case. What do you think @tomolopolis ?

Also, any plans of adding functionality to show the ontology and tui / semantic_type (they're the same right? I logged that at https://github.com/CogStack/MedCAT/issues/138)

**Comment by CBezzAH** [comment]
Hi @sandertan thanks for logging the issue as we too are experiencing this issue. 

![Issue1](https://user-images.githubusercontent.com/91935906/135968133-2b76d16b-5fb8-4e29-b83f-38022d95912a.jpg)

I noticed it still has the annotations registered if you click the annotation summary button, however we're pausing annotations in the mean time as we're not sure what is happening behind the scenes with the CDB, etc.

![Issue2](https://user-images.githubusercontent.com/91935906/135968148-8df9d6c6-a64b-4da0-b6aa-f5bbe82ff544.jpg)

**Comment by tomolopolis** [comment]
Fixed in https://github.com/CogStack/MedCATtrainer/releases/tag/v2.1.5
