### ISSUE TITLE
Authentication information required?

### ISSUE THREAD

**Issue by a2dsouza** [CogStack/MedCATtrainer#5]
After building the Docker container and launching the application via `docker-compose up -d' and navigating to http://localhost:8001, the application frontend asks for a user name and a password. Can you tell me what should be typed in there?

(screenshot attached)
<img width="1994" alt="Screen Shot 2019-10-31 at 5 15 33 PM" src="https://user-images.githubusercontent.com/7331062/67992424-3b81b080-fc02-11e9-9485-e4670577e08f.png">

**Comment by tomolopolis** [comment]
Hi - all these details will be in the upcoming README, but as you've asked :).

The container runs a vanilla django app, that by default has no users / super users. So you'll need to add them via the django manage.py script on the container. Further users, (i.e. annotators for a given project) can be added via the django admin ui.

1) First get the running container name:
`docker ps

> CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                            NAMES
> 62b9a2380f30        cattrainer_nginx           "nginx -g 'daemon of…"   2 days ago          Up 2 days           80/tcp, 0.0.0.0:8001->8000/tcp   cattrainer_nginx_1
> 93168cc98c15        cattrainer_medcattrainer   "/home/run.sh"           2 days ago          Up 2 days           8000/tcp                         **cattrainer_medcattrainer_1**

2) login into the container running django, its the name indicated in **bold**:

`docker exec -it cattrainer_medcattrainer_1 bash`

> root@93168cc98c15:/home/api# 

3) Create the super user username and password by following the prompts.

`root@93168cc98c15:/home/api# python manage.py createsuperuser`

> Username (leave blank to use 'root'): 
> Email address: 
> Password: 
> Password (again): 
> The password is too similar to the username.
> This password is too short. It must contain at least 8 characters.
> This password is too common.
> Bypass password validation and create user anyway? [y/N]: y
> Superuser created successfully.

I used the 'root' default super user, and specified a simple password. I'd advise following the password prompts for complexity etc.

4) You can now login into the front end using the specified username / password.

5) To upload documents and begin annotating, you'll first need to create a project via the admin page.  localhost:8001/admin/.

I'll create a brief guide for this today.

**Comment by a2dsouza** [comment]
Perfect, that all worked as expected. Thank you, and also thanks for the updated README.

**Comment by tomolopolis** [comment]
No worries. Feel free to raise more issues / submit a PR if you think things could improve in places. Our team is actively using this for Clinical note annotation collection so will find probabaly find it useful also :)
