### ISSUE TITLE
Import Concepts Can't Impute a Preferred Name

### ISSUE THREAD

**Issue by arfenarf** [CogStack/MedCATtrainer#54]
When I load concepts from a CDB that has many CUIs with no value in "Preferred Concept," `_import_concepts()` loads only the CUI value into `concept.pretty_name`, which really handicaps an annotator when they search for an alternative.

I was able to get the desired behavior by calling:

`concept.pretty_name = cdb.get_name(cui)` instead. Is there a reason for using `cui2preferred_name`?

```
def _import_concepts(id):
    from medcat.cdb import CDB
    concept_db = ConceptDB.objects.get(id=id)
    cdb = CDB.load(concept_db.cdb_file.path)

    # Get all existing cuis for this CDB
    existing_cuis = set(Concept.objects.filter(cdb=id).values_list('cui', flat=True))

    for cui in cdb.cui2names.keys():
        if cui not in existing_cuis:
            concept = Concept()
            concept.pretty_name = cdb.cui2preferred_name.get(cui, cui)
```

**Comment by tomolopolis** [comment]
Good spot. Changed: 19662c66d8e2039d86a93fbbe89afd2c9be77ec4
