### ISSUE TITLE
Feature enhancement: allow concept import and metatask creation from API

### ISSUE THREAD

**Issue by zack-kimble** [CogStack/MedCATtrainer#56]
Assuming I already have users, I've found that I can automate almost every step of project creation via the API. The two things I can't automate are importing concepts from a CDB to the Trainer's concept table and create meta tasks.
Either the ability to directly POST concepts or trigger the `_import_concepts` background task would be greatly appreciated. Allowing `post` to metatasks and metatask values would also be great.

**Comment by tomolopolis** [comment]
agreed - both (or all three depending on how you look at it 🤷 )  should be exposed via APIs. Feel free to submit a PR if you like

**Comment by tomolopolis** [comment]
cc581534b2adbd55f3a66703d4a0b2122d61b7a8

**Comment by zack-kimble** [comment]
Thanks for the enhancement!
