### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by PeijinV5** [CogStack/MedCATtrainer#72]
Hi I am trying to download my annotation, but encountered this error. Could you please advide?
<img width="1428" alt="Screen Shot 2022-04-27 at 5 12 26 PM" src="https://user-images.githubusercontent.com/20632498/165632093-a9401224-af6d-4223-bb8d-9fb6a16df671.png">

**Comment by tomolopolis** [comment]
Should be fixed with this: de53ff3b4038eccbcae42c9096787c7cf67f18f1, will be available in the next release or the :latest dockerHub image in an hour or so.

**Comment by tomolopolis** [comment]
latest release is available on docker-hub 2.3.0, git pull the latest docker-compose.yml, its configured there
