### ISSUE TITLE
Concept lookup not working. Concepts not being imported into SOLR. 

### ISSUE THREAD

**Issue by sreesankarp** [CogStack/MedCATtrainer#88]
@tomolopolis 

It seems like "api/import-cdb-concepts" is not called anywhere
Cant find it anywhere in source except for urls.py

We manually made the call and it created a new collection in solr.
<img width="324" alt="image" src="https://user-images.githubusercontent.com/37147746/181282847-bc978dbf-87a6-42c1-9c34-f0f78f4aea9b.png">

<img width="448" alt="image" src="https://user-images.githubusercontent.com/37147746/181283471-84ebb82e-163d-46b8-9cee-74f847a31db1.png">

**Comment by bramiozo** [comment]
Can you describe how you imported the cdb through with the Solr api? We are having the same problem, the Solr collection is not made/populated.

**Comment by bramiozo** [comment]
This should also do it :D.
![image](https://user-images.githubusercontent.com/11760064/193682832-3c5dbff8-82b8-44a9-b231-cde5adfe72a4.png)

**Comment by bramiozo** [comment]
Ah this should also do it ;)

![image](https://user-images.githubusercontent.com/11760064/193682964-e284f0de-2efe-414e-a34c-526cae0e7a71.png)

**Comment by tomolopolis** [comment]
yep looks like you've got it. This process is also explained here - albeit not in the clearest way 
https://medcattrainer.readthedocs.io/en/latest/project_admin.html#concept-picker-cdb-concept-import
