### ISSUE TITLE
No check mark after importing concepts

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#93]
I imported the concepts from a CDB in Solr using the "Concept dbs" -> "Import concepts" functionality in the admin panel, and the concepts do seem imported because I can find them in the Concept Picker, but there's no check mark on the overview-page. Does this suggest the import process was not fully completed?

<img width="136" alt="image" src="https://user-images.githubusercontent.com/9624990/198964838-7f24d38d-4bec-464f-9d4d-e9fcdc04f462.png">

Logs of the medcattrainer container:
```
INFO 2022-10-31 08:24:25,599 admin.py l:707:Importing concepts for collection cdb_id_1
[pid: 72|app: 0|req: 29/29] 192.168.16.4 () {66 vars in 1480 bytes} [Mon Oct 31 08:24:25 2022] POST /admin/api/conceptdb/ => generated 0 bytes in 18 msecs (HTTP/1.0 302) 7 headers in 260 bytes (1 switches on core 0)
[pid: 72|app: 0|req: 30/30] 192.168.16.4 () {60 vars in 1373 bytes} [Mon Oct 31 08:24:25 2022] GET /admin/api/conceptdb/ => generated 4551 bytes in 31 msecs (HTTP/1.0 200) 7 headers in 395 bytes (1 switches on core 0)
[pid: 72|app: 0|req: 31/31] 192.168.16.4 () {54 vars in 1133 bytes} [Mon Oct 31 08:24:25 2022] GET /admin/jsi18n/ => generated 3223 bytes in 5 msecs (HTTP/1.0 200) 4 headers in 132 bytes (1 switches on core 0)
[pid: 72|app: 0|req: 32/32] 192.168.16.4 () {54 vars in 1189 bytes} [Mon Oct 31 08:24:25 2022] GET /favicon.ico => generated 962 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 109 bytes (1 switches on core 0)
INFO 2022-10-31 08:24:34,805 tasks.py l:257:Running api.admin.import_concepts_from_cdb
WARNING 2022-10-31 08:24:35,212 cdb.py l:682:The CDB was exported by an unknown version of MedCAT.
INFO 2022-10-31 08:24:37,501 solr_utils.py l:116:Uploading 5000 to solr collection cdb_id_1
INFO 2022-10-31 08:24:39,346 solr_utils.py l:119:Successfully uploaded 5000 concepts to solr collection cdb_id_1
INFO 2022-10-31 08:24:39,360 solr_utils.py l:116:Uploading 5000 to solr collection cdb_id_1
INFO 2022-10-31 08:24:39,793 solr_utils.py l:119:Successfully uploaded 5000 concepts to solr collection cdb_id_1
INFO 2022-10-31 08:24:39,805 solr_utils.py l:116:Uploading 3124 to solr collection cdb_id_1
INFO 2022-10-31 08:24:40,661 solr_utils.py l:119:Successfully uploaded 3124 concepts to solr collection cdb_id_1
INFO 2022-10-31 08:24:40,661 solr_utils.py l:152:Successfully uploaded cdb cuis / names to solr collection cdb_id_1
INFO 2022-10-31 08:24:40,754 solr_utils.py l:155:13124 Concepts now searchable
INFO 2022-10-31 08:24:40,815 tasks.py l:52:Ran task and deleting api.admin.import_concepts_from_cdb
```

The reported 13124 imported concepts is the expected number.

**Comment by tomolopolis** [comment]
hi @sandertan - the check market should be green if:
- the project is configured with a CDB that has been imported into solr. e.g. the admin page of the project shows:
![Screenshot 2022-11-25 at 15 12 02](https://user-images.githubusercontent.com/6503604/204013743-c1561206-9949-4d3e-8f2d-d00329be56a8.png)
- the solr concept search service has imported this exact model instance - as the solr index uses the django object id in the creation of the index: ![Screenshot 2022-11-25 at 15 15 36](https://user-images.githubusercontent.com/6503604/204014050-d58d0c7e-bf99-46a9-b34d-44926a221de7.png)

The endpoint used by the front to get the import list is: 
```/api/concept-db-search-index-created/?cdbs='<cdb_id>'```

I'll edit this slightly now so you can at least query all the solr indices, as right now you have to list a cdb_id to lookup

Potentially you have another CDB instance uploaded to solr / configured with the project?

**Comment by sandertan** [comment]
@tomolopolis Selecting "CDB search filter" indeed resulted in the green check mark for "Concepts Imported"! I missed this in the documentation. Perhaps we can expand the documentation on this, and/or align the naming of this functionality.

**Comment by tomolopolis** [comment]
no worries - I've added some improvements here (in the latest commit)  #102 , 
you'll see a lil' tooltip to hopefully indicate what the cross actually means :)
![Screenshot 2022-11-29 at 11 06 38](https://user-images.githubusercontent.com/6503604/204513424-9ecac9bf-0474-4871-9086-6b173a074159.png)
