### ISSUE TITLE
Search for synonyms in Concept Picker/Lookup

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#94]
Hi @tomolopolis . In the current Concept Picker/Lookup, only preferred/primary/pretty names of concepts are provided in the dropdown list. Did you consider making is possible to also search through synonyms? An annotator might not know the primary name of the concept, unless he has access to a list/table view of all concepts.

Additionally, it might be useful to also show the Concept ID and semantic type in the dropdown list; this makes it easier to distinguish ambiguous terms.

If this is functionality you'd like to have but currently don't have resources to implement it, I can discuss in our team if this is something we can add.

**Comment by tomolopolis** [comment]
#102 couple of improvements in this PR so far:
- concept ID is now shown

Synonyms should be relatively starightforward so that's next

types is a little tricky without it looking a little messy - the SNOMED CDBs have potentially multiple top level parents (or pseudo type terms).

**Comment by tomolopolis** [comment]
@sandertan  - finally got around to cleaning up some of this concept picker stuff. With the latest changes on #114 
- removed the concept model in django, this isn't needed and leads to confusion for maintenance  
- solr now indexes everything to do with a concept, all metadata (synonyms, concept descriptions etc.)
- cleaned up the query / searching for concepts in solr. Performs an exact match i.e. the query for myocardial infarction will send:
  - q=name:"myocardial infarction"^2 OR synonyms:"myocardial infarction"
- show synonyms on ConceptSummary and AddAnnotation views, again if present.
- re-directed /api/concepts to solr directly - for dev mode and in prod builds

**Comment by tomolopolis** [comment]
Feel free to re-open if these latest changes still don't cut the mustard!

There's still some visual stuff to be done to be more helpful...
