### ISSUE TITLE
Text between angle brackets not (correctly) displayed

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#97]
We're using a de-identification algorithm which masks protected health information in text. The algorithm replaces names, dates and other PHI with a tag between angle brackets, such as `<PATIENT-1>` and `<DATE-1>`. We noticed that the current MedCATTrainer does not display these tags correctly.

Example for text `On <DATE-1> <PATIENT-1> was diagnosed`:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/9624990/199180211-e6426dca-5b4e-4d8e-a944-baaadacd969e.png">

**Comment by tomolopolis** [comment]
#111
