### ISSUE TITLE
Option to disable loading the examples

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATtrainer#99]
For a non-English, non-UMLS concept universe or production instance it might be useful to disable loading the examples. This can be manually commented out in `run.sh` when building the Docker image, but it might be nice to make this configurable, for example with Docker build args.

**Comment by tomolopolis** [comment]
Fixed in #118

**Comment by tomolopolis** [comment]
I should say - this is now available in `env` and `env-prod` under `/envs/`

`LOAD_EXAMPLES=1` # will load the example dataset, cdb, vocab etc, 0 will not.
